
find_package(PythonInterp REQUIRED)

execute_process(
	COMMAND ${PYTHON_EXECUTABLE} "${CMAKE_SOURCE_DIR}/script/getSystemString.py"
	OUTPUT_VARIABLE SYSSTRING
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

set(EXTERNAL_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../Coati_External")
set(EXTERNAL_SRC "${EXTERNAL_ROOT}/src")
if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
	set(EXTERNAL_BUILD "${EXTERNAL_ROOT}/${SYSSTRING}/Debug")
else()
	set(EXTERNAL_BUILD "${EXTERNAL_ROOT}/${SYSSTRING}/Release")
endif()

