string(REGEX MATCH "64" MATCH_64 ${CMAKE_GENERATOR})

if("${MATCH_64}" STREQUAL "64")
	message(STATUS "Target is 64 bits")
		if (WIN32)
			set(WINXXBITS Win64)
		endif(WIN32)
else()
	message(STATUS "Target is 32 bits")
		if (WIN32)
			set(WINXXBITS Win32)
		endif(WIN32)
endif()